<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <PlatformTarget>x64</PlatformTarget>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWpf>true</UseWpf>
    <Configurations>Debug N21;Debug N22;Debug N23;Debug N24;Debug N25</Configurations>
    <Configurations>$(Configurations);Release N20;Release N21;Release N22;Release N23;Release N24;Release N25</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('N21'))">
    <CADVersion>21.0.5699.3427</CADVersion>
    <DefineConstants>$(DefineConstants);A21</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('N22'))">
    <CADVersion>22.0.6013.3747</CADVersion>
    <DefineConstants>$(DefineConstants);A22</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('N23'))">
    <CADVersion>23.0.6177.4117</CADVersion>
    <TargetFramework>net6.0-windows</TargetFramework>
    <DefineConstants>$(DefineConstants);A23</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('N24'))">
    <CADVersion>24.0.6377.4326</CADVersion>
    <TargetFramework>net6.0-windows</TargetFramework>
    <DefineConstants>$(DefineConstants);A24</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('N25'))">
    <CADVersion>25.0.6785.4733</CADVersion>
    <TargetFramework>net6.0-windows</TargetFramework>
    <DefineConstants>$(DefineConstants);A25</DefineConstants>
  </PropertyGroup>
  <PropertyGroup>
    <Version>$(CADVersion)</Version>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Description>A Project Support for developer in Autocad And Civil3D </Description>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="nanoCAD.Platform.NET" Version="$(CADVersion)">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="CsvHelper" Version="16.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />

    <None Remove="FileSample\sample_base.dwg" />
    <Resource Include="FileSample\sample_base.dwg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="ZoomToObject.cs">
      <DependentUpon>XrefPathExtractor.cs</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
